# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d701469cb0d14fe54fa909b84dc61c756f11b7b8d129c8972d57f63b2353e5c0de020a3e35f014867e8d7f4765842a1dc6c948dbb23bd63d369d0e6911065a48

test:
  secret_key_base: 3d36eabb3a4c1af4d230b62278e90cc7a007ab54519b734b1197d3d156aff8947a2134e7e2b1b7b1bedef55af90ef8b25ba393d0821f6b862075e7d679eea92f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
